# Configuration for RDC1 (Secondary Data Center)
routing_config: "resources/rdc1/routing.yaml"

subjects:
  - Networks
  - Routing
  - Firewall

devices:
  intranet_routers:
    - R2
    - R3
    - R4
    - R5
    - R6
  internet_routers:
    - ISP
  other_routers:
    - R1

networks:
  # defined by the name of the switch
  intranet_lan_networks:
    - Sw-Adm
    - Sw-Troncal
    - SW-DC
    - SW-Comp
    - SW-Esc
    - wlan-Inv
    - wlan-Reu

  # name of the routers combined
  intranet_p2p_networks:
    - R5<>R6

  # name of the internet routers combined
  internet_networks:
    - ISP<>R4
    - ISP<>R2
    - ISP<>R1

  other_networks:
    - wlan-Casa
