# Configuration for RDC1 (Secondary Data Center)
class_name: "rdc1"
routing_config: "resources/rdc1/routing.yaml"
max_prefixes_per_network: 1

subjects:
  - Networks
  - Routing
  - Firewall

devices:
  intranet_routers:
    - R2
    - R3
    - R4
    - R5
    - R6
  internet_routers:
    - ISP
  other_routers:
    - R1

networks:
  # defined by the name of the switch
  intranet_lan_networks:
    - name: Sw-Adm
      mask: 28
      last_octet: 160
    - name: Sw-Troncal
      mask: 27
      last_octet: 128
    - name: SW-DC
      mask: 24
      last_octet: 0
    - name: SW-Comp
      mask: 29
      last_octet: 112
    - name: SW-Esc
      mask: 27
      last_octet: 64
    - name: wlan-Inv
      mask: 26
      last_octet: 0
    - name: wlan-Reu
      mask: 28
      last_octet: 96

  # name of the routers combined
  intranet_p2p_networks:
    - name: R5<>R6
      mask: 30
      last_octet: 120

  # name of the internet routers combined
  internet_networks:
    - name: ISP<>R4
      mask: 24
    - name: ISP<>R2
      mask: 24
    - name: ISP<>R1
      mask: 24

  other_networks:
    - name: wlan-Casa
      mask: 24

firewall:
  iptables_table:
    columns:
      - chain
      - src
      - dst
      - iif
      - oif
      - mark
      - target
