
# Configuration for RDC2 (Primary Data Center)
class_name: "rdc2"
routing_config: "resources/rdc2/routing.yaml"
max_prefixes_per_network: 2

subjects:
  - Networks
  - RADVD
  - Routing
  - RPDB
  - Firewall
  - Tunneling

devices:
  intranet_routers:
    - R1-DC
    - R2
    - R3
    - R4
    - R5
    - R6

  internet_routers:
    - ISP-Intranet
    - ISP-Casa

  other_routers:
    - R-Casa

networks:
  # defined by the name of the switch
  intranet_lan_networks:
    - name: SwDataCenter
      mask: 64
    - name: WVentas
      mask: 64
    - name: SwVentas
      mask: 64
    - name: WGuest
      mask: 64
    - name: SwAdmin
      mask: 64
    - name: SwOfiAdmin
      mask: 64

  # name of the routers combined
  intranet_p2p_networks:
    - name: R4<>R1-DC
      mask: 127
    - name: R4<>R5
      mask: 127
    - name: R5<>R6
      mask: 127
    - name: R5<>R3
      mask: 127
    - name: R4<>R3
      mask: 127
    - name: R2<>R3
      mask: 127
    - name: R2<>R4
      mask: 127

  # name of the internet routers combined
  internet_networks:
    - name: ISP-Casa<>R-Casa
      mask: 24
    - name: R2<>ISP-Intranet
      mask: 24
    - name: ISP-Casa<>ISP-Intranet
      mask: 24

  other_networks:
    - name: R-Casa<>PC-Casa
      mask: 64